Func NameOfTroop($kind, $plurial = 0)
	Switch $kind
		Case $eBarb
			Return "바바리안"
		Case $eArch
			Return "아처"
		Case $eGobl
			Return "고블린"
		Case $eGiant
			Return "자이언트"
		Case $eWall
			Return "해골돌격병"
		Case $eWiza
			Return "마법사"
		Case $eBall
			Return "해골비행선"
	    Case $eHeal
			Return "치유사"
	    Case $eDrag
			Return "드래곤"
	    Case $ePekk
			Return "페카"
		Case $eMini
			Return "미니언"
		Case $eHogs
			Return "호그라이더"
		Case $eValk
			Return "발키리"
		Case $eWitc
			Return "마녀"
		Case $eGole
			Return "골렘"
		Case $eLava
			Return "라바하운드"
		Case $eKing
			Return "바바리안킹"
		Case $eQueen
			Return "아처퀸"
		Case $eCastle
			Return "클랜성"
		Case $eLSpell
			Return "번개마법"
		Case $eHSpell
			Return "회복마법"
		Case $eRSpell
			Return "분노마법"
	    Case $eJSpell
			Return "이동마법"
		Case $eFSpell
			Return "얼음마법"
		Case $ePSpell
			Return "독마법"
		Case $eESpell
			Return "지진마법"
		Case $eHaSpell
			Return "신속마법"
		Case Else
			Return ""
	EndSwitch
EndFunc   ;==>NameOfTroop
